baseURL = "https://blog.woodgie.net/"
languageCode = "en-us"

paginate = "10"
theme = "mainroad"
disqusShortname = ""
googleAnalytics = ""

[Author]
  name = "Woodgie"
  bio = "I'm just this geek, you know?"
  avatar = "media/images/Avengers-Iron-Man-icon.png"

[Params]
  subtitle = "subtitle"
  description = "In which I try to explain things I didn't understand before."
  copyright = "copyright"
  opengraph = true
  schema = true
  twitter_cards = true
  readmore = false
  authorbox = true
  toc = true
  pager = true
  post_meta = ["author", "date", "categories", "translations"]
  mainSections = ["posts", "blog", "news"]
  dateformat = "2006-01-02"
  mathjax = true
  mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js"
  mathjaxConfig = "TeX-AMS-MML_HTMLorMML"
  googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700"
  #customCSS = ["css/custom.css"]
  #customJS = ["js/custom.js"]

[Params.style.vars]
  highlightColor = "#e22d30"
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "media/images/banner_picture.png"
  title = "woodgie.net"
  subtitle = "I'm just this geek, you know?"

[Params.sidebar]
  home = "right"
  list = "left"
  single = false
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]


[Params.widgets]
  recent_num = 5
  tags_counter = true

[Params.widgets.social]
  twitter = "_Woodgie"
  linkedin = "wthunter"
  
[[Params.widgets.social.custom]]
  title = "MacSdmins Slack"
  url = "https://macadmins.slack.com/"
  icon = "slack.svg"
  
[[Params.widgets.social.custom]]
  title = "Reddit"
  url = "https://www.reddit.com/user/woodgie2"
  icon = "reddit.svg"